### ISSUE TITLE
Manage via DockerHub

### ISSUE THREAD

**Issue by phrazzld** [phrazzld/lantern#4]

**Comment by phrazzld** [comment]
https://hub.docker.com/r/phrazzld/lantern

**Comment by bhanikita** [comment]
Lolol thanks for raping me ✌️✌️✌️killing myself today. Thanks for nothing. Btw I dropped out of college. Sorry for being stupid, guess I'm a whore. Look on the bright side, I'll stop bothering you. Peace.
